apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: demo-springboot
        name: demo-springboot
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
---
kind: Service
apiVersion: v1
metadata:
  name: demo
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
  externalIPs:
    - 192.168.1.117
